# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdd4598d73338e6728c0a88812b28e4dab6cf9084d3dbba67a5e7fb81b6d07e0b743570257eedf36e3127f03ccc97d9649639f9ab4bc134156872e7ec6046db7

test:
  secret_key_base: 2f3f6d94faf632e5bc28485e327b537e5e684a80b2ca6379ea6463cd94d654ebc1fb8a8c22cb7d15963a2d95e3affda4889f2f60be74de608c7c6915f7baf64c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
